# Generated by Django 5.2 on 2025-05-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="id_tg",
            field=models.CharField(
                blank=True,
                help_text="Введите Chat-ID Telegram",
                max_length=50,
                null=True,
                verbose_name="id_tg",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Укажите город",
                max_length=20,
                null=True,
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Введите Email",
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
    ]
