# Generated by Django 5.2 on 2025-05-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_phone_number_user_id_tg_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
