# Generated by Django 5.2 on 2025-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers_remove_user_id_tg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите Chat-ID Telegram",
                max_length=50,
                null=True,
                verbose_name="Chat-ID Telegram",
            ),
        ),
    ]
