# Generated by Django 5.2 on 2025-05-03 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=100,
                        verbose_name="place",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку",
                        verbose_name="time",
                    ),
                ),
                (
                    "act",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка",
                        max_length=120,
                        verbose_name="act",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=True,
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки",
                        verbose_name="pleasant_habit",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки",
                        verbose_name="periodicity",
                    ),
                ),
                (
                    "prize",
                    models.CharField(
                        help_text="Награда после выполнения",
                        max_length=100,
                        verbose_name="prize",
                    ),
                ),
                (
                    "lead_time",
                    models.PositiveSmallIntegerField(
                        help_text="Время на выполнение",
                        max_length=100,
                        verbose_name="lead_time",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Публикация в общий доступ"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habit.habits",
                        verbose_name="related_habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Создатель привычки",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
