# Generated by Django 5.2 on 2025-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="lead_time",
            field=models.PositiveSmallIntegerField(
                help_text="Время на выполнение", verbose_name="lead_time"
            ),
        ),
    ]
